### ISSUE TITLE
Crashing - probably on too-fast unsubscribe based on the trace

### ISSUE THREAD

**Issue by Iiridayn** [deepstreamIO/deepstream.io-provider-search-rethinkdb#57]
```
--------------------------------------------------------------------------------
5:49:47 PM:303 | Initialising RethinkDb Connection
5:49:47 PM:324 | Initialising Deepstream connection
      _                     _                              _
   __| | ___  ___ _ __  ___| |_ _ __ ___  __ _ _ __ ___   (_) ___
  / _` |/ _ \/ _ \ '_ \/ __| __| '__/ _ \/ _` | '_ ` _ \  | |/ _ \
 | (_| |  __/  __/ |_) \__ \ |_| | |  __/ (_| | | | | | |_| | (_) |
  \__,_|\___|\___| .__/|___/\__|_|  \___|\__,_|_| |_| |_(_)_|\___/
                 |_|
 =========================   starting   ==========================
Can't connect! Deepstream server unreachable on ws://localhost:6020/deepstream
5:49:47 PM:523 | Connection to deepstream established
5:49:47 PM:523 | listening for search[\?].*
5:49:47 PM:524 | rethinkdb search provider ready

app/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'name' of null
    at Search._populateList (app/node_modules/deepstream.io-provider-search-rethinkdb/sr
c/search.js:130:91)
    at Search._readChange (app/node_modules/deepstream.io-provider-search-rethinkdb/src/
search.js:98:12)
    at app/node_modules/rethinkdb/cursor.js:261:20
    at tryCatcher (app/node_modules/bluebird/js/main/util.js:26:23)
    at Promise.successAdapter (app/node_modules/bluebird/js/main/nodeify.js:23:30)
    at Promise._settlePromiseAt (app/node_modules/bluebird/js/main/promise.js:582:21)
    at Promise._settlePromises (app/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (app/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (app/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (app/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by layanto** [comment]
I too get this crash but at different code section
```
C:\project\server\node_modules\bluebird\js\main\async.js:43
        fn = function () { throw arg; };
                           ^

TypeError: Cannot read property 'name' of null
    at Search._processInitialValues (C:\project\server\node_modules\deepstream.io-provider-search-rethinkdb\src\search.js:144:65)
    at Search._readChange (C:\project\server\node_modules\deepstream.io-provider-search-rethinkdb\src\search.js:103:12)
    at C:\project\server\node_modules\rethinkdb\cursor.js:261:20
    at tryCatcher (C:\project\server\node_modules\bluebird\js\main\util.js:26:23)
    at Promise.successAdapter (C:\project\server\node_modules\bluebird\js\main\nodeify.js:23:30)
    at Promise._settlePromiseAt (C:\project\server\node_modules\bluebird\js\main\promise.js:582:21)
    at Promise._settlePromiseAtPostResolution (C:\project\server\node_modules\bluebird\js\main\promise.js:248:10)
    at Async._drainQueue (C:\project\server\node_modules\bluebird\js\main\async.js:128:12)
    at Async._drainQueues (C:\project\server\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\project\server\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by layanto** [comment]
I am probably doing something wrong but I can reliably trigger this crash on my backend search provider with the following client code:

const deepstream = require('deepstream.io-client-js')
const ds = deepstream('127.0.0.1:6020')
```
ds.login({
    username: 'johndoe',
    password: 'secret'
}, function (success, data) {
    const queryString = JSON.stringify({
        table: 'user',
        query: true
    })
    const list = ds.record.getList('search?' + queryString)

    list.subscribe((entries) => {
        console.log(entries)
    })
})

ds.on('error', (error, event, topic) => {
    console.log(error, event, topic)
})
```
Run the above client code in node, then terminate the process (by Ctrl+C or closing the terminal). This immediately crash the backend search provider.
